# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Xuzao
subtitle: 虚构制造
email: contact@xuzao.net
description: " An international research, art and education program
for speculative design and manufacturing"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xuzao.net" # the base hostname & protocol for your site
twitter_username: xuzaostudio
github_username:  xuzao

# Build settings
markdown: kramdown
